# Generated by Django 4.2.2 on 2023-06-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
